config/routes.rb
Rails.application.routes.draw do
  resources :group_keywords
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html  
  root to: "home#index"

  # get json data for API
  get "userGroup.json", to: "home#getUserGroups"

  # sidekiq web 
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group_keyword.rb
class GroupKeyword < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/group_keywords_controller.rb
class GroupKeywordsController < ApplicationController
  before_action :set_group_keyword, only: %i[ show edit update destroy ]

  # GET /group_keywords or /group_keywords.json
  def index    
    @group_keywords = GroupKeyword.all
  end

  # GET /group_keywords/1 or /group_keywords/1.json
  def show
  end

  # GET /group_keywords/new
  def new
    @group_keyword = GroupKeyword.new
    @group_keyword.groupid = !params['groupid'].nil? ? params['groupid'] : ''
    @group_keyword.userid = !params['userid'].nil? ? params['userid'] : ''
  end

  # GET /group_keywords/1/edit
  def edit
  end

  # POST /group_keywords or /group_keywords.json
  def create
    @group_keyword = GroupKeyword.new(group_keyword_params)

    respond_to do |format|
      if @group_keyword.save
        # schedule job for selected recored
        # execute at every 5 minutes, ex: 12:05, 12:10, 12:15...etc
        jobId = Sidekiq::Cron::Job.create(name: "Hard worker - every 5min userid-#{@group_keyword.id}", cron: '*/5 * * * *', class: 'FbkeywordNotificationJob', args: @group_keyword.id) 

        format.html { redirect_to @group_keyword, notice: "Group keyword was successfully created." }
        format.json { render :show, status: :created, location: @group_keyword }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group_keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_keywords/1 or /group_keywords/1.json
  def update
    respond_to do |format|
      if @group_keyword.update(group_keyword_params)
        format.html { redirect_to @group_keyword, notice: "Group keyword was successfully updated." }
        format.json { render :show, status: :ok, location: @group_keyword }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group_keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_keywords/1 or /group_keywords/1.json
  def destroy
    @group_keyword.destroy
    respond_to do |format|
      format.html { redirect_to group_keywords_url, notice: "Group keyword was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_keyword
      @group_keyword = GroupKeyword.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_keyword_params
      params.require(:group_keyword).permit(:groupid, :userid, :keyword)
    end
end

app/controllers/home_controller.rb
require 'net/http'
class HomeController < ApplicationController
    
    def index
        @apiData = getGroupsData(getGroupDataUrl)      
    end

    # get usesr group data 
    def getUserGroups
        begin
            json_data = JSON.parse(request.body.read)
            if !json_data["userId"].empty?
              userId = json_data["userId"]
              userToken = json_data["userToken"]
            else
              render json: { status: "failed", "errors": [{ "field": "Invalid Json Data" }] }, status: 400
            end

            #success
            url = getGroupDataUrl(userId,userToken)
            jsonData = getGroupsData(urlInfo)
            render json: jsonData, status: 200
        rescue => e            
            render json: { status: "failed", "errors": ["message": e.message] }, status: 400           
        end
        
    end

    private
    def getGroupDataUrl(id = '',token = '')
        # please set your own user id and token hear for default url
        @userId = id.empty? ? "4697735986919539" : id
        @userToken = token.empty? ? "EAAOFiojcxXQBAEzRD1VBLZCSnuS8Jzs4Nclt1WxMnZCZAT48BtWebZAxcuzmllHZBKhKHDpe9IVBHKFVAXMnTE2o0EhoNujufukxomJ0ZCNHDzC6r1B1Ir7xn7GmpflV4oI3faRhQQXm1VfXDS7h4JtgFVyY5vE0awgfqYMgzw2cIZCxZCt8Xp6XKZAKQLJFBa8ZBap6iTzjlTjztvBnFzEspXJGPpRyYOKSrvEbXIOW76McvLGBF3piIf" : token
        return "https://graph.facebook.com/v11.0/#{@userId}/groups?access_token=#{@userToken}"
    end

    def getGroupsData(urlInfo = '')
        # check if url info is nil
        url = URI(urlInfo) 
        http = Net::HTTP.new(url.host, url.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
        request = Net::HTTP::Get.new(url)       
        request["content-type"] = 'application/json'
        response = http.request(request)        
        apiData = JSON.parse(response.read_body)
        return apiData
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_keywords_helper.rb
module GroupKeywordsHelper
end

app/views/group_keywords/_form.html.erb
<%= form_with(model: group_keyword) do |form| %>
  <% if group_keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group_keyword.errors.count, "error") %> prohibited this group_keyword from being saved:</h2>

      <ul>
        <% group_keyword.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :groupid %>
    <%= form.text_field :groupid %>
  </div>

  <div class="field">
    <%= form.label :userid %>
    <%= form.text_field :userid %>
  </div>

  <div class="field">
    <%= form.label :keyword %>
    <%= form.text_field :keyword %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/group_keywords/edit.html.erb
<h1>Editing Group Keyword</h1>

<%= render 'form', group_keyword: @group_keyword %>

<%= link_to 'Show', @group_keyword %> |
<%= link_to 'Back', group_keywords_path %>

app/views/group_keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Group Keywords</h1>

<table>
  <thead>
    <tr>
      <th>Groupid</th>
      <th>Userid</th>
      <th>Keyword</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_keywords.each do |group_keyword| %>
      <tr>
        <td><%= group_keyword.groupid %></td>
        <td><%= group_keyword.userid %></td>
        <td><%= group_keyword.keyword %></td>
        <td><%= link_to 'Show', group_keyword %></td>
        <td><%= link_to 'Edit', edit_group_keyword_path(group_keyword) %></td>
        <td><%= link_to 'Destroy', group_keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/group_keywords/new.html.erb
<h1>New Group Keyword</h1>

<%= render 'form', group_keyword: @group_keyword %>

<%= link_to 'Back', group_keywords_path %>

app/views/group_keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Groupid:</strong>
  <%= @group_keyword.groupid %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @group_keyword.userid %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @group_keyword.keyword %>
</p>

<%= link_to 'Edit', edit_group_keyword_path(@group_keyword) %> |
<%= link_to 'Back', group_keywords_path %>

app/views/home/index.html.erb

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '991254978282868',
      cookie     : true,
      xfbml      : true,
      version    : 'v11.0'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
   
    /*FB.getLoginStatus(function(response) {
        console.log(response);
        statusChangeCallback(response);
    });*/

    function fbLogin(){
        FB.login(function(response) {
            if(response.authResponse){
                fbAfterLogin();
            }   
        });
    }

    function fbAfterLogin() {
        FB.getLoginStatus(function(response) {
            if(response.status === "connected") {
                console.log(JSON.stringify(response));            
                FB.api("/me",function (resp) {
                    console.log(JSON.stringify(resp));            
                });
            }
        });
    }
</script>
<center><div>
<fb:login-button 
  scope="public_profile,email"
  onlogin="fbLogin();">
</fb:login-button>

</div>
<div>
<table border="1">
    <tr>
        <th>Group Name</th>
        <th>Group Id</th>
        <th>Action</th>
    </tr>
    
    <% if !@apiData['data'].nil? %>
        <% @apiData['data'].each do |groupData|%>
        <tr>
            <td><%=groupData['name'].nil? ? "-" : groupData['name']%></td>
            <th><%=groupData['id'].nil? ? "-" : groupData['id']%></th>
            <th><%= link_to 'New Group Keyword', new_group_keyword_path(userid: @userId,groupid: groupData['id']) %></th>
            </tr>
        <%end%>
    <%end%>
    
</table>
</div>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TstApiFB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>